# Generated by Django 4.2.23 on 2025-07-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('nebulosa', 'Naisagem'), ('estrela', 'Estrela'), ('galaxia', 'Galaxia'), ('planeta', 'Planeta')], default='nebulosa', max_length=50),
        ),
    ]
